# Generated by Django 3.1.5 on 2021-02-05 16:35

from django.db import migrations, models
import storages.s3_book_image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book_filters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, max_length=3000, null=True)),
                ('image', models.FileField(storage=storages.s3_book_image.S3BookImageStorage(), upload_to='')),
                ('isbn', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0)),
                ('orig_price', models.FloatField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('in_stock', models.IntegerField(default=0)),
                ('pages_count', models.IntegerField(default=100)),
                ('paper_type', models.CharField(max_length=100)),
                ('tags', models.ManyToManyField(blank=True, related_name='books', to='book_filters.Tag')),
            ],
        ),
    ]
