# Generated by Django 3.1.5 on 2021-02-13 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='favorite',
            new_name='chosen',
        ),
    ]
