# Generated by Django 3.1.5 on 2021-02-17 20:14

from django.db import migrations, models
import storages.s3_book_image


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20210215_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(storage=storages.s3_book_image.S3BookImageStorage(), upload_to=''),
        ),
    ]
