# Generated by Django 3.1.5 on 2021-03-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_auto_20210106_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(default='+380000000000', max_length=20),
        ),
    ]
