# Generated by Django 3.1.5 on 2021-02-06 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_filters', '0002_author_publishing_series'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name_plural': 'series'},
        ),
    ]
