# Generated by Django 3.1.5 on 2021-02-07 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_filters', '0004_auto_20210207_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taggroup',
            options={'ordering': ['favorite']},
        ),
    ]
