# Generated by Django 3.1.5 on 2021-02-07 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_filters', '0005_auto_20210207_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taggroup',
            options={'ordering': ['-favorite']},
        ),
    ]
