# Generated by Django 3.1.5 on 2021-02-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_filters', '0006_auto_20210207_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'statuses',
            },
        ),
    ]
