# Generated by Django 3.1.5 on 2021-02-13 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_filters', '0007_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taggroup',
            options={'ordering': ['-chosen']},
        ),
        migrations.RenameField(
            model_name='author',
            old_name='favorite',
            new_name='chosen',
        ),
        migrations.RenameField(
            model_name='taggroup',
            old_name='favorite',
            new_name='chosen',
        ),
    ]
