name: Deploy Client
on:
  push:
    branches:
      - master
    paths: 'frontend/**/*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          cd frontend
          npm install
      - name: Build
        env:
          REACT_APP_BACKEND_BASE_URL: 'https://api.nicolaus.com.ua'
          REACT_APP_CHATBOT_BASE_URL: 'https://viberbksdlv.tk'
          REACT_APP_CHATBOT_API_KEY: ${{ secrets.CHATBOT_API_KEY }}
        run: |
          cd frontend
          npm run build
      - name: Enable Amazon
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        uses: chrislennon/action-aws-cli@v1.1
      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_S3_CLIENT_REGION }}
          SOURCE_DIR: 'frontend/build'
        run: |
          aws s3 rm --recursive s3://${{ secrets.AWS_S3_CLIENT_BUCKET }}
          aws s3 sync frontend/build/ s3://${{ secrets.AWS_S3_CLIENT_BUCKET }}
